# Redis
# spring.data.redis.host=Redis??
# spring.data.redis.port=6379
# spring.data.redis.password=Redis????

# MySQL
# spring.datasource.url=jdbc:mysql://???:??/???
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=DB??
# spring.datasource.password=DB????

# spring
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# S3
aws.s3.key-prefix=prod
aws.s3.bucket=time-memories-image-952441831392-ap-northeast-2-an
aws.credentials.access-key=${AWS_ACCESS_KEY}
aws.credentials.secret-key=${AWS_SECRET_KEY}